-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.olist_customers
(
    customer_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    customer_unique_id character varying(50) COLLATE pg_catalog."default",
    customer_zip_code_prefix character varying(10) COLLATE pg_catalog."default",
    customer_city character varying(50) COLLATE pg_catalog."default",
    customer_state character varying(5) COLLATE pg_catalog."default",
    CONSTRAINT olist_customers_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.olist_geolocation
(
    geolocation_zip_code_prefix character varying(10) COLLATE pg_catalog."default",
    geolocation_lat numeric(10, 6),
    geolocation_lng numeric(10, 6),
    geolocation_city character varying(50) COLLATE pg_catalog."default",
    geolocation_state character varying(5) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.olist_order_items
(
    order_id character varying(50) COLLATE pg_catalog."default",
    order_item_id integer,
    product_id character varying(50) COLLATE pg_catalog."default",
    seller_id character varying(50) COLLATE pg_catalog."default",
    shipping_limit_date timestamp without time zone,
    price numeric(10, 2),
    freight_value numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS public.olist_order_payments
(
    order_id character varying(50) COLLATE pg_catalog."default",
    payment_sequential integer,
    payment_type character varying(20) COLLATE pg_catalog."default",
    payment_installments integer,
    payment_value numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS public.olist_order_reviews
(
    review_id character varying(50) COLLATE pg_catalog."default",
    order_id character varying(50) COLLATE pg_catalog."default",
    review_score integer,
    review_comment_title character varying(100) COLLATE pg_catalog."default",
    review_comment_message text COLLATE pg_catalog."default",
    review_creation_date timestamp without time zone,
    review_answer_timestamp timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.olist_orders
(
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    customer_id character varying(50) COLLATE pg_catalog."default",
    order_status character varying(20) COLLATE pg_catalog."default",
    order_purchase_timestamp timestamp without time zone,
    order_approved_at timestamp without time zone,
    order_delivered_carrier_date timestamp without time zone,
    order_delivered_customer_date timestamp without time zone,
    order_estimated_delivery_date timestamp without time zone,
    CONSTRAINT olist_orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.olist_products
(
    product_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_category_name character varying(100) COLLATE pg_catalog."default",
    product_name_length integer,
    product_description_length integer,
    product_photos_qty integer,
    product_weight_g integer,
    product_length_cm integer,
    product_height_cm integer,
    product_width_cm integer,
    CONSTRAINT olist_products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.olist_sellers
(
    seller_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    seller_zip_code_prefix character varying(10) COLLATE pg_catalog."default",
    seller_city character varying(50) COLLATE pg_catalog."default",
    seller_state character varying(5) COLLATE pg_catalog."default",
    CONSTRAINT olist_sellers_pkey PRIMARY KEY (seller_id)
);

ALTER TABLE IF EXISTS public.olist_order_items
    ADD CONSTRAINT fk_items_order FOREIGN KEY (seller_id)
    REFERENCES public.olist_sellers (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.olist_order_items
    ADD CONSTRAINT fk_olist_order_items FOREIGN KEY (product_id)
    REFERENCES public.olist_products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.olist_order_items
    ADD CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id)
    REFERENCES public.olist_orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.olist_order_payments
    ADD CONSTRAINT fk_payments_orders FOREIGN KEY (order_id)
    REFERENCES public.olist_orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.olist_order_reviews
    ADD CONSTRAINT fk_reviews_orders FOREIGN KEY (order_id)
    REFERENCES public.olist_orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.olist_orders
    ADD CONSTRAINT fk_orders FOREIGN KEY (customer_id)
    REFERENCES public.olist_customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;